### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by g-kartik** [lawrensylvan/linkedin-learning-courses-downloader#12]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle linkedin-learning-courses-downloader@0.2.0~prestart: linkedin-learning-courses-downloader@0.2.0
6 info lifecycle linkedin-learning-courses-downloader@0.2.0~start: linkedin-learning-courses-downloader@0.2.0
7 verbose lifecycle linkedin-learning-courses-downloader@0.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle linkedin-learning-courses-downloader@0.2.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/media/myunix/Storage/hack/lawren/linkedin-learning-courses-downloader-master/node_modules/.bin:/home/myunix/miniconda3/bin:/home/myunix/miniconda3/condabin:/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle linkedin-learning-courses-downloader@0.2.0~start: CWD: /media/myunix/Storage/hack/lawren/linkedin-learning-courses-downloader-master
10 silly lifecycle linkedin-learning-courses-downloader@0.2.0~start: Args: [ '-c', 'node ./test.js' ]
11 silly lifecycle linkedin-learning-courses-downloader@0.2.0~start: Returned: code: 1  signal: null
12 info lifecycle linkedin-learning-courses-downloader@0.2.0~start: Failed to exec start script
13 verbose stack Error: linkedin-learning-courses-downloader@0.2.0 start: `node ./test.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid linkedin-learning-courses-downloader@0.2.0
15 verbose cwd /media/myunix/Storage/hack/lawren/linkedin-learning-courses-downloader-master
16 verbose Linux 5.8.0-44-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error linkedin-learning-courses-downloader@0.2.0 start: `node ./test.js`
22 error Exit status 1
23 error Failed at the linkedin-learning-courses-downloader@0.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by pendave** [comment]
Greasemonkey userscript can fulfil the requirment for download videos as well as subtitles, even in batch mode. 
Works for library login :)

Please try this basic script first: https://greasyfork.org/en/scripts/428184-linkedin-learning-videos-download-directly-from-listing-out-basic-version-for-videos-only
